### ISSUE TITLE
error 400

### ISSUE THREAD

**Issue by ylyparis** [keikai/dev-ref#1]
Hi Hawk,

I can reach the home page. However no further link works. I got error 400.

Within the debugger there's the below error message :
"crbug/1173575, non-JS module files deprecated.
(anonymous) @ VM10:6772"

Thanks,
yly

**Comment by hawkchen** [comment]
the error you mentioned is highly related to VScode, please see https://itsmycode.com/crbug-1173575-non-js-module-files-deprecated/
As the README said, do you start the project with the Tomcat plugin or jetty plugin?

**Comment by hawkchen** [comment]
Recently, I found a bug that the links on the home page contain `\` when running on Windows. It will cause a browser encodes `\` into `%5c` and the links don't work anymore. Please pull the latest update to get the fix.

**Comment by ylyparis** [comment]
It works fine now !

Thanks a lot Hawk.
