### ISSUE TITLE
http://localhost:8080/dev-ref not working

### ISSUE THREAD

**Issue by Aritra1704** [keikai/dev-ref#2]
the URL is not working after successful run.
![image](https://user-images.githubusercontent.com/5179501/166907716-e346e3a9-152e-47f4-8cd3-2bc55cfbe8d0.png)
![image](https://user-images.githubusercontent.com/5179501/166907832-e0cae3e3-5ec5-4331-b515-7474a73dfdd4.png)

**Comment by hawkchen** [comment]
According to your 2nd screenshot, an EDB postgres is also listening port 8080. If that's the case, I suppose your application server might not start successfully if it also listens to 8080. Is there any error on your server console?

**Comment by Aritra1704** [comment]
Modified the ports to 8010 and I'm able to see the ref URL.
